first draft Services
DaanVanVugt/ignitioncomputing pull request #52
Opened 2024-06-27 13:11 UTC by ylegrand-ignitioncomputing

A few edits done on: research software, machine learning Verification and validation

Somewhat changes to description, better pictures

All pictures are free-use, no attribution needed:
https://www.pexels.com/license/

Still needed: visualizations, case descriptions for preconnet, Celsian, office photo's

Please create a subfeature branch for your own commits, then merge into this branch

Fixes #50

2024-06-28 08:38 UTC, DaanVanVugt requested changes

2024-06-28 08:38 UTC, DaanVanVugt commented on _services/fullstack.md
> +    allowing a near-native experience on the popular mobile platforms from a single code base. We bring strong experience with web-application development. Our team has done projects with in Ruby on
no spaces between attributes

2024-06-28 08:38 UTC, DaanVanVugt commented on _services/fullstack.md
> +    allowing a near-native experience on the popular mobile platforms from a single code base. We bring strong experience with web-application development. Our team has done projects with in Ruby on
physiscs

2024-06-28 08:38 UTC, DaanVanVugt commented on _services/fullstack.md
>  image: /assets/img/service/2.jpg
can be removed completely

2024-06-28 08:38 UTC, DaanVanVugt commented on _services/research-software.md
> +            <p>We have extensive experience with Computational Fluid Dynamics and Magnetohydrodynamics, using non-linear MHD codes like <a href="">JOREK</a>. We have contributed to <a href="{% link _
'are contributing'

2024-07-02 06:53 UTC, DaanVanVugt commented on _services/research-software.md
> +            <p>We have extensive experience with Computational Fluid Dynamics and Magnetohydrodynamics, using non-linear MHD codes like <a href="">JOREK</a>. We are contributing to <a href="{% link _
jorek.eu, (developed instead of developped, ancd we haven't really done the physics of glass ovens, perhaps you can reduce the claim there a bit)

2024-07-02 06:53 UTC, DaanVanVugt commented on _services/modelling.md
> +            Potentiam subtilitatis nostris lorem ipsum physicae exemplaribus liberamus, vestras ideas in rem convertentes. Innovate, simulare, et excellere cum nostro programmate provecto. Lorem ipsu
lipsum

2024-07-02 14:54 UTC, ylegrand-ignitioncomputing commented on _services/research-software.md
> +            <p>We have extensive experience with Computational Fluid Dynamics and Magnetohydrodynamics, using non-linear MHD codes like <a href="">JOREK</a>. We are contributing to <a href="{% link _
Yes, I meant we developed a tool (Preconnet) that was applicable to different kinds of models. But I guess that shouldn't be mentioned in this section at all, given it is not physics modelling.

2024-10-10 14:20 UTC, ylegrand-ignitioncomputing commented on _services/visualisation.md
@SBlokhuizen kan jij de hoofd image veranderen en eventueel de eerste intro paragraaf herschrijven?

2024-10-10 14:20 UTC, ylegrand-ignitioncomputing commented on _services/performance.md
@Yannicked zou jij deze kunnen herschrijven?

2024-10-10 14:22 UTC, ylegrand-ignitioncomputing commented
- [ ]  Visualisation (add own visualization): @SBlokhuizen 
- [ ] Visualisation (new intro page): @SBlokhuizen 
- [ ] Physics Based Machine learning: Alan?
- [ ] Performance Optimzation: @Yannicked 
- [ ] Integrated Models and Software Interfacing: ?

2024-10-10 14:35 UTC, ylegrand-ignitioncomputing commented on _services/modelling.md
@DaanVanVugt zou je hiervoor een aanzet kunnen geven?

2024-10-15 08:22 UTC, ylegrand-ignitioncomputing commented on _services/modelling.md
> +            <p> Nuclear fusion is a wide field, with many physics phenomena, many different experiments, calculations and simulations done by a diverse set of research groups. Data is generated over
```suggestion
            <p> Nuclear fusion is a vast field, with numerous physics phenomena, diverse experimental setups, complex calculations, and simulations conducted by various research teams.  Given that data is generated over a variety of geometries and physical parameters, structured frameworks and interfaces are necessary to ensure seamless interoperability between teams and their respective data structures.</p>
```

2024-10-15 08:22 UTC, ylegrand-ignitioncomputing commented on _services/modelling.md
> +            We have developed a <a href="_posts/news/2021-03-21-ITER-IMAS-Python.md">pythonic, flexible interface</a> to data stored with the IMAS Access Layer, and are working on enabling access wit
```suggestion
            We have developed a <a href="/news/2021/03/21/ITER-IMAS-Python">pythonic, flexible interface</a> for data stored with the IMAS Access Layer. We are now working on enabling access with the modern data processing ecosystem, using tooling such as xarray, netCDF, intake et cetera.
```

2024-10-15 08:22 UTC, ylegrand-ignitioncomputing commented on _services/modelling.md
> +            We have developed a <a href="_posts/news/2021-03-21-ITER-IMAS-Python.md">pythonic, flexible interface</a> to data stored with the IMAS Access Layer, and are working on enabling access wit
De eerste zin loopt niet helemaal lekker, wat wordt er precies bedoelt? Dat we de acces layer ontwikkeld hebben? Of dat we een interface hebben gemaakt voor data dat met de IMAS access layer opgeslagen is?

2024-10-15 08:22 UTC, ylegrand-ignitioncomputing commented on _services/modelling.md
> +            This framework is the base of the new ITER Pulse Design Simulator Tool that we are developing, in consortium with CEA and Université Côte d'Azur, which will combine magnetic equilibrium e
```suggestion
            This framework is the foundation of the ITER Pulse Design Simulator Tool, which we are developing in consortium with CEA and Université Côte d'Azur. This new simulation tool will combine magnetic equilibrium evolution simulation with core transport modelling, and integrate it with the ITER plasma control systems through synthetic diagnostics.
```

Als je fancy will done kan je ook 'novel simulation tool'  zeggen ipv 'new simulation tool'

2024-10-15 08:22 UTC, ylegrand-ignitioncomputing commented on _services/modelling.md
> +            Complementing simulators with ML surrogates is a way to profit from potential performance increases while remaining certain of results.
ChatGPT raad het volgende aan, maar ik ben nieet zeker of dat de originele betekenis denkt:

> Developing a predictive and interpretable digital twin requires robust physics-based models. While machine learning methods can aid this process, they should not serve as the sole foundation. Enhancing simulators with ML surrogates allows us to leverage potential performance gains while ensuring the reliability and accuracy of results

2024-10-16 11:58 UTC, Yannicked commented on _includes/about.html
> +                    <p>Do you think we might be able to help you? <a href="/contact">Get in touch!</a></p>
Ik vind die tweede wel nice
```suggestion
                    <p>Ready to see how we can help? <a href="/contact">Get in touch!</a></p>
```

2024-10-16 12:03 UTC, Yannicked commented on _services/modelling.md
> +            We have developed a <a href="_posts/news/2021-03-21-ITER-IMAS-Python.md">pythonic, flexible interface</a> to data stored with the IMAS Access Layer, and are working on enabling access wit
Ik zou et cetera eruit laten

2024-10-16 12:09 UTC, Yannicked commented on contact.html
> +                    <a href="mailto:{{site.email}}?subject=Meeting request&body=Dear Ignition Computing team,%0D%0DI hope this message finds you well. I am interested in scheduling a meeting to discu
Je kan ook iets als dit doen: https://workspace.google.com/resources/appointment-scheduling/. Test voorbeeldje: https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ1XL1pwHy7dkcKULhySqqgnKPIOXq1yongkPa15EeBYufmTA9W4SrEwY_bz2iStgP5zAs1sgdKh

2024-10-16 12:11 UTC, Yannicked commented on _services/modelling.md
> +            We have developed a <a href="_posts/news/2021-03-21-ITER-IMAS-Python.md">pythonic, flexible interface</a> to data stored with the IMAS Access Layer, and are working on enabling access wit
```suggestion
            We have developed a <a href="/news/2021/03/21/ITER-IMAS-Python">pythonic, flexible interface</a> for data stored with the IMAS Access Layer. We are now working on enabling access with the modern data processing ecosystem, using tooling such as xarray, netCDF and intake.
```

2024-10-16 12:23 UTC, Yannicked commented on assets/img/service/pexels-thisisengineering-3862632-min.jpg
Let's clean up the images in a different pr. We also have a lot of unused images floating around

2024-10-16 12:42 UTC, Yannicked commented on assets/img/service/pexels-thisisengineering-3862632-min.jpg
#69

2024-10-16 13:25 UTC, Yannicked commented on _services/modelling.md
> +            Complementing simulators with ML surrogates is a way to profit from potential performance increases while remaining certain of results.
```suggestion
            Developing an easy to interpret digital twin with predictive power, requires robust physics-based models. While machine learning methods can aid this process, they should not serve as the sole foundation. Enhancing simulators with ML surrogates allows us to leverage potential performance gains while ensuring the reliability and accuracy of results
```

2024-10-16 13:29 UTC, Yannicked commented on contact.html
> +                    <a href="mailto:{{site.email}}?subject=Meeting request&body=Dear Ignition Computing team,%0D%0DI hope this message finds you well. I am interested in scheduling a meeting to discu
#70

2024-10-16 13:42 UTC, Yannicked submitted a review, later dismissed
LGTM

2024-10-16 13:48 UTC, Yannicked approved these changes

2024-10-16 13:48 UTC, merged