Open Application draft
DaanVanVugt/ignitioncomputing pull request #56
Opened 2024-07-05 09:39 UTC by ylegrand-ignitioncomputing

Just an idea, still want to shorten it some more.

2024-07-09 12:12 UTC, DaanVanVugt requested changes

2024-07-09 12:12 UTC, DaanVanVugt commented on _posts/careers/2024-07-05-Open-Application.md
> +- Salary in the range of €2800 to €3500
can leave out the specifics and what we ask

2024-07-09 12:26 UTC, ylegrand-ignitioncomputing commented on _posts/careers/2024-07-05-Open-Application.md
> +- Lots of opportunities to grow
```suggestion

```

2024-07-09 12:26 UTC, ylegrand-ignitioncomputing commented on _posts/careers/2024-07-05-Open-Application.md
> +- Lots of opportunities to grow
just remove all of it @DaanVanVugt or greatly summarize it?

2024-07-09 13:06 UTC, DaanVanVugt commented on _posts/careers/2024-07-05-Open-Application.md
> +- Lots of opportunities to grow
propose something ;) But I think for an open application we don't have to define so much, that can be discussed by pointing to the most recent position for instance.

2024-09-03 14:47 UTC, ylegrand-ignitioncomputing commented on _posts/careers/2024-07-05-Open-Application.md
> +- Lots of opportunities to grow
combined it with the text before.

2024-09-03 15:02 UTC, Yannicked commented on _posts/careers/2024-09-03-Open-Application.md
> +### About US
```suggestion
### About Us
```

2024-09-03 15:03 UTC, Yannicked commented on _posts/careers/2024-09-03-Open-Application.md
> +We are continuosly looking for physics software developers, simulation software engineers, experts in high-performance and/or parallel computing, people with a background in nuclear fusion, engineeri
```suggestion
We are continuosly looking for physics software developers, simulation software engineers, experts in high-performance and/or parallel computing, people with a background in nuclear fusion, engineering mathematics, computer science and physics. Do you fit one of these descriptions? Do you want to help build software for the future of science? Whether you are looking for a full-time role, internship or traineeship, feel free to
```

2024-09-03 15:03 UTC, Yannicked commented on _posts/careers/2024-09-03-Open-Application.md
> +Our culture is focussed on cooperation, growth and a healthy work-life balance. We are open to flexible work-arrangements such as (partial) work from home and Payed Time Off (PTO). At Ignition Comput
_We're open to PTO_ sounds a bit odd 🤔

2024-10-15 05:54 UTC, DaanVanVugt requested changes

2024-10-15 05:54 UTC, DaanVanVugt commented on _posts/careers/2024-09-03-Open-Application.md
> +We are continuosly looking for physics software developers, simulation software engineers, experts in high-performance and/or parallel computing, people with a background in nuclear fusion, engineeri
typo, continuously. Also, 'we are continuously looking' feels a bit desperate? I would try to rephrase things from the applicant's perspective, to indicate that we have a lot of interesting work, so it might be worthwhile to make an open application

2024-10-15 05:54 UTC, DaanVanVugt commented on _posts/careers/2024-09-03-Open-Application.md
> +- [ITER](https://iter.org), the world's biggest nuclear fusion project where we have multiple running projects such as working on the underlying data structures for experimental data ([IMASPy](https:
the imaspy popen-source project is years behind the 'real' one (and we should probably make a notice on the projectp age)

2024-10-15 05:54 UTC, DaanVanVugt commented on _posts/careers/2024-09-03-Open-Application.md
> +- Consulting for various Dutch tech companies such as [Celsian](https://www.celsian.nl/) and [Plasma Matters](https://plasimo.phys.tue.nl/index.php).
CelSian

2024-10-15 05:54 UTC, DaanVanVugt commented on _posts/careers/2024-09-03-Open-Application.md
> +- Consulting for an American fusion start-up (currently in stealth).
stealth mode

2024-10-15 05:54 UTC, DaanVanVugt commented on _posts/careers/2024-09-03-Open-Application.md
> +To apply, send your job application, which includes CV and cover letter, to <careers@ignitioncomputing.com>
I think we can avoid the cover letter, I'd be more interested in a work sample

2024-10-15 08:30 UTC, ylegrand-ignitioncomputing commented on _posts/careers/2024-09-03-Open-Application.md
> +- Consulting for various Dutch tech companies such as [Celsian](https://www.celsian.nl/) and [Plasma Matters](https://plasimo.phys.tue.nl/index.php).
```suggestion
- Consulting for various Dutch tech companies such as [CelSian](https://www.celsian.nl/) and [Plasma Matters](https://plasimo.phys.tue.nl/index.php).
```

2024-10-15 08:33 UTC, ylegrand-ignitioncomputing commented on _posts/careers/2024-09-03-Open-Application.md
> +To apply, send your job application, which includes CV and cover letter, to <careers@ignitioncomputing.com>
```suggestion
To apply, send your job application, which includes CV and a salient coding sample (e.g., GitHub repository, code snippet, or project portfolio) , to <careers@ignitioncomputing.com>
```

2024-10-17 09:01 UTC, ylegrand-ignitioncomputing commented on _posts/careers/2024-09-03-Open-Application.md
> +We're always excited to connect with talented physics software developers, computer scientists, simulation engineers, and those with expertise in nuclear fusion, engineering mathematics, high-perform
```suggestion
We're always happy to connect with talented physics software developers, computer scientists, simulation engineers, and those with expertise in nuclear fusion, engineering mathematics, high-performance computing, or physics. If you're excited about shaping the future of science through innovative software, we'd love to hear from you.
```

2024-10-17 09:03 UTC, ylegrand-ignitioncomputing commented on _posts/careers/2024-09-03-Open-Application.md
> +We're always excited to connect with talented physics software developers, computer scientists, simulation engineers, and those with expertise in nuclear fusion, engineering mathematics, high-perform
```suggestion
Are you passionate about complex problem-solving,  high-tech systems, and software engineering? We're always happy to connect with talented physics software developers, computer scientists, simulation engineers, and those with expertise in nuclear fusion, engineering mathematics, high-performance computing, or physics. If you're excited about shaping the future of science through innovative software, we'd love to hear from you.
```

2024-10-17 09:21 UTC, Yannicked approved these changes
![bama](https://github.com/user-attachments/assets/615a28d8-cd69-4abd-9fac-4b69c5170fac)

2024-10-24 14:10 UTC, DaanVanVugt commented
let's not have an open application for now, we'll reopen this in a few months. @Yannicked can you remove the existing position in a different PR?

2024-10-24 14:10 UTC, closed without merging