add mit r&d ai post
DaanVanVugt/ignitioncomputing pull request #60
Opened 2024-07-18 08:20 UTC by DaanVanVugt

Also check with Celsian before merge.

2024-07-18 09:45 UTC, ylegrand-ignitioncomputing commented on _posts/news/2024-07-11-ITER Public Private Workshop.md
> +Some startups are working on the well-established [magnetic confinement fusion](https://en.wikipedia.org/wiki/Magnetic_confinement_fusion) pathways such as Stellarators and Tokamaks while harnessing
What changed here?

2024-07-18 14:11 UTC, DaanVanVugt commented on _posts/news/2024-07-11-ITER Public Private Workshop.md
> +Some startups are working on the well-established [magnetic confinement fusion](https://en.wikipedia.org/wiki/Magnetic_confinement_fusion) pathways such as Stellarators and Tokamaks while harnessing
newline at the end of the file I expect.

2024-07-18 14:21 UTC, ylegrand-ignitioncomputing requested changes

2024-07-18 14:35 UTC, ylegrand-ignitioncomputing commented on _posts/news/2024-07-18-MIT R&D AI.md
> +The project is expected to result in improved quality prediction models leading to substantial economic and environmental gains. Through more efficient feed-stock use and energy consumption, each gla
```suggestion
The glass-melting process can take up to multiple days. This makes glass production difficult. Temperature and material fluctuations have implications for the final product. Product quality issues, such as bubbles in glass, may arise. This can lead to the loss of large batches of glass, totaling multiple days of production. New developments in machine learning and simulation provide more accurate predictions of glass quality.

The project is expected to result in improved quality prediction models leading to substantial economic and environmental gains. Through more efficient feed-stock use and energy consumption, each glass oven could save energy costs in the range of  € 250.000 to € 1.250.000 per year as well as reducing CO2 and nitrous oxide emissions. This undeniably positive expected impact fits with our vision of supporting the sustainable industry of the future.
```

2024-07-18 14:38 UTC, SBlokhuizen commented on _posts/news/2024-07-18-MIT R&D AI.md
> +The SME Innovation Stimulus for Regional and Top Sectors (MIT in Dutch) encourages SMEs to develop creative initiatives. These top ten sectors in the Netherlands have been designated as those that ha
```suggestion
The SME Innovation Stimulus for Regional and Top Sectors (MIT in Dutch) encourages Small and Medium-sized Enterprises (SMEs) to develop creative initiatives. These top ten sectors in the Netherlands have been designated as those that have the potential to solve global problems and help boost the country’s economy and competitiveness. [The MIT R&D AI is the dedicated stimulus program for innovative collaboration projects by SMEs to deploy innovative AI tools in the top sectors](http://ained.nl/ained-geeft-stevige-impuls-aan-mkb-voor-ontwikkeling-en-toepassing-van-ai-2/ ).
```

2024-07-18 14:38 UTC, SBlokhuizen commented on _posts/news/2024-07-18-MIT R&D AI.md
> +Our technology- partner CelSian has decades of experience in CFD tools used for the quality prediction of glass making. We will be integrating and adapting Preconnet with CelSians market-leading GTM-
```suggestion
Our technology- partner CelSian has decades of experience in CFD tools used for the quality prediction of glass making. We will be integrating and adapting Preconnet with CelSian's market-leading GTM-X tool (see article picture). Preconnet is a machine-learning based tool to accelerate simulations by generating preconditioners, initial guesses and proposing solver configurations. Preconnet is a versatile tool that was developed for plasma simulations in a previous project in collaboration with [Plasimo](/posts/news/2022/01/10/Preconnet_Teamup). Its functionality, however, can be extended to other fields as well.
```

2024-07-18 14:42 UTC, ylegrand-ignitioncomputing commented on _posts/news/2024-07-18-MIT R&D AI.md
> +Our technology- partner CelSian has decades of experience in CFD tools used for the quality prediction of glass making. We will be integrating and adapting Preconnet with CelSians market-leading GTM-
Als je zegt dat preconnet versatile is, dan hoef je toch niet te vertellen dat het in andere velden toepasbaar is?

2024-07-19 08:29 UTC, ylegrand-ignitioncomputing approved these changes

2024-07-19 08:30 UTC, merged